name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 20]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run linting
        run: npm run lint
        
      - name: Run tests
        run: npm test
        
      - name: Build package
        run: npm run build
        
      - name: Verify build output
        run: |
          ls -la dist/
          echo "Checking for required files..."
          test -f dist/index.js && echo "✓ index.js exists"
          test -f dist/index.d.ts && echo "✓ index.d.ts exists"
          test -f dist/types.js && echo "✓ types.js exists"
          test -f dist/types.d.ts && echo "✓ types.d.ts exists"
          test -f dist/xmlTypes.js && echo "✓ xmlTypes.js exists"
          test -f dist/xmlTypes.d.ts && echo "✓ xmlTypes.d.ts exists"
          test -d dist/components && echo "✓ components directory exists"
          test -d dist/utils && echo "✓ utils directory exists"
          
      - name: Check package size
        run: |
          echo "Package size:"
          du -sh dist/
          echo "Number of files:"
          find dist/ -type f | wc -l 