name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run linting
        run: npm run lint
        
      - name: Run tests
        run: npm test
        
      - name: Build package
        run: npm run build
        
      - name: Verify build output
        run: |
          ls -la dist/
          echo "Checking for required files..."
          test -f dist/index.js && echo "✓ index.js exists"
          test -f dist/index.d.ts && echo "✓ index.d.ts exists"
          test -f dist/types.js && echo "✓ types.js exists"
          test -f dist/types.d.ts && echo "✓ types.d.ts exists"
          test -f dist/xmlTypes.js && echo "✓ xmlTypes.js exists"
          test -f dist/xmlTypes.d.ts && echo "✓ xmlTypes.d.ts exists"
          test -d dist/components && echo "✓ components directory exists"
          test -d dist/utils && echo "✓ utils directory exists"
          
      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          
      - name: Create GitHub release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            ## What's Changed
            
            This release includes:
            - Bug fixes and improvements
            - Enhanced documentation
            - Better TypeScript support
            
            ## Installation
            
            ```bash
            npm install xml-rulekit
            ```
            
            ## Usage
            
            ```typescript
            import { XmlRuleBuilder, xmlToRules } from 'xml-rulekit';
            ```
            
            For more information, see the [README](https://github.com/${{ github.repository }}#readme).
          draft: false
          prerelease: false 